print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print("최은관")
print("우리 가족")
print("대한민국")
print("I am enjoying 30 days of python")

print(type(10)) 
print(type(9.8))
print(type(3.14)) 
print(type(4 - 4j)) 
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("최은관"))
print(type("우리 가족"))
print(type("국가 이름"))